
const words = [
  { spanish: [`nadie`], english: [`nobody`] },
  // { spanish: [`ustedes`], english: [`you`, `they`] },
  // { spanish: [`despertar con pereza`], english: [`to wake up with laziness`] },
  // { spanish: [`si`], english: [`if`] },
  // { spanish: [`yo`], english: [`I`] },
  // { spanish: [`tu`, `usted`], english: [`you`] },
  // { spanish: [`el`], english: [`he`] },
  // { spanish: [`ella`], english: [`she`] },
  // { spanish: [`nosotros`, `nosotras`], english: [`we`] },
  // { spanish: [`ellos`, `ellas`], english: [`they`] },
  // { spanish: [`comer`], english: [`to eat`] },
  // { spanish: [`yo como`], english: [`I eat`] },
  // { spanish: [`tu comes`], english: [`you eat`] },
  // { spanish: [`el come`], english: [`he eats`] },
  // { spanish: [`ella come`], english: [`she eats`] },
  // { spanish: [`ellos comen`], english: [`they eat`] },
  // { spanish: [`nosotros comemos`], english: [`we eat`] },
  // { spanish: [`oran`], english: [`to pray`] },
  // { spanish: [`amar`], english: [`to love`] },
  // { spanish: [`vivir`], english: [`to live`] },
  // { spanish: [`llegar`], english: [`to arrive`] },
  // { spanish: [`tarde`], english: [`late`] },
  // { spanish: [`siempre`], english: [`always`] },
  // { spanish: [`contigo`], english: [`together`] },
  // { spanish: [`leer`], english: [`to read`] },
  // { spanish: [`voz alta`], english: [`loud voice`] },
  // { spanish: [`ver`], english: [`to see`] },
  // { spanish: [`desde lejos`], english: [`from far`] },
  // { spanish: [`cielo estrellado`], english: [`starry sky`] },
  // { spanish: [`alguien`], english: [`someone`, `somebody`, `anyone`] },
  // { spanish: [`soy`], english: [`I am`] },
  // { spanish: [`eres`], english: [`you are`] },
  // { spanish: [`es`], english: [`he is`, `she is`] },
  // { spanish: [`somos`], english: [`we are`] },
  // { spanish: [`son`], english: [`they are`] },
  // { spanish: [`de que parte de argentina eres`], english: [`which part of argentina are you from`] },
  // { spanish: [`cerca de londres`], english: [`close to london`] },
  // { spanish: [`nos vemos`], english: [`we see each other`] },
  // { spanish: [`nosotros vemos un gato`], english: [`we see the cat`] },
  // { spanish: [`campo`], english: [`countryside`] },
  // { spanish: [`fue robado`], english: [`it was stolen`] },
  // { spanish: [`medio ambiente`], english: [`the environment`] },
  // { spanish: [`al comienzo`], english: [`at the start`] },
  // { spanish: [`da miedo`], english: [`it's scary`] },
  // { spanish: [`barrio`], english: [`neighbourhood`] },
  // { spanish: [`afuera de londres`], english: [`outside of london`] },
  // { spanish: [`muy lento`], english: [`very slow`] },
  // { spanish: [`no muy seguido`], english: [`not very often`] },
  // { spanish: [`descansar`], english: [`to rest`] },
  // { spanish: [`cantar`], english: [`to sing`] },
  // { spanish: [`peluqueria`], english: [`hair salon`] },
  // { spanish: [`abrazar`], english: [`to hug`] },
  // { spanish: [`tener que`], english: [`have to`] },
  // { spanish: [`yo tengo que`], english: [`I have to`] },
  // { spanish: [`hago mis tareas después de clase`], english: [`I do my homework after class`] },
  // { spanish: [`qué voy a hacer con el resto de mi vida`], english: [`what am I going to do with the rest of my life`] },  
];

export default words;

